# Импорты

In [26]:
import pandas as pd
import numpy as np

# Рекурсия

In [ ]:
# Дано число и количество раз, которое его нужно умножить на себя. 
# Необходимо написать рекурсивную функцию multiply(num, times), 
# которая умножает число само на себя заданное целое натуральное количество раз (или 0 раз). 
# Каждый элемент списка multiply — это результат одного умножения. 
# Использовать встроенный оператор ** для возведения в степень запрещено. 
# Пользуйтесь только умножением *.

# Например, для числа 2 и количества умножений 4 результат вычисляется так:
# 2 умножить 4 раза = (((2 * 2) * 2) * 2) = 16

num, times = 3, 3

def multiply(num, times):
    if times == 0:
        return 1
    return num * multiply(num, times - 1)

res = multiply(num, times)
print(res)

27

In [ ]:
# Необходимо написать рекурсивную функцию factorial(k), которая вычисляет факториал числа k. 
# Каждый элемент списка factorial — это результат одного умножения на следующее число. 
# Использовать встроенные функции для вычисления факториала запрещено. 
# Пользуйтесь только умножением * и рекурсией.

# Например, для числа 5 факториал вычисляется так:
# 5! = 5 * 4 * 3 * 2 * 1 = 120

k = 5

def factorial(k):
    if k == 0 or k == 1:
        return 1
    return k * factorial(k - 1)

res = factorial(k)
print(res)

120

In [ ]:
# Дана строка, содержащая только английские буквы (большие и маленькие). 
# Необходимо написать функцию add_brackets(), которая принимает на вход строку. 

# Функция должна добавлять в строку открывающиеся и закрывающиеся скобки по следующему образцу:
# "example" → "e(x(a(m)p)l)e"

# До середины добавляются открывающие скобки, после середины — закрывающие. 
# Если длина строки равна чётному числу, в скобках, расположенных в середине, должно быть два символа.

In [30]:
line = 'example'

def add_brackets(line):
    if len(line) <= 2:
        return line
    return line[0] + '(' + add_brackets(line[1: -1]) + ')' + line[-1]

add_brackets(line)

'e(x(a(m)p)l)e'

# Алгоритмы

In [ ]:
numbers = [45, 35, 25, 55, 15, 65, 95, 85, 105, 75]

n = len(numbers)
for i in range(n - 1):
    for j in range(n - i - 1):
        if numbers[j] > numbers[j + 1]:
            numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]
numbers

[15, 25, 35, 45, 55, 65, 75, 85, 95, 105]

In [ ]:
# Чтение чисел из stdin
numbers = [45, 35, 25, 55, 15, 65, 95, 85, 105, 75]

# Допишите ваш код здесь

def bubble_sort_mod(numbers):
    n = len(numbers)
    for i in range(n - 1):
        swaped = False
        for j in range(n - i - 1):
            if numbers[j] > numbers[j + 1]:
                numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]
                swaped = True
        if not swaped:
            break
            
bubble_sort_mod(numbers)

print(numbers)

[15, 25, 35, 45, 55, 65, 75, 85, 95, 105]

In [ ]:
# Чтение чисел из stdin
numbers = [45, 35, 25, 55, 15, 65, 95, 85, 105, 75]

# Допишите ваш код здесь

def selection_sort(numbers):
    n = len(numbers)
    for i in range(n - 1):
        min_index = i
        for j in range(i + 1, n):
            if numbers[j] < numbers[min_index]:
                min_index = j

        min_value = numbers.pop(min_index)
        numbers.insert(i, min_value)
            
selection_sort(numbers)

print(numbers)

[15, 25, 35, 45, 55, 65, 75, 85, 95, 105]

In [ ]:
# Чтение чисел из stdin
numbers = [45, 35, 25, 55, 15, 65, 95, 85, 105, 75]

# Допишите ваш код здесь

def selection_sort(numbers):
    n = len(numbers)
    for i in range(n - 1):
        min_index = i
        for j in range(i + 1, n):
            if numbers[j] < numbers[min_index]:
                numbers[min_index], numbers[j] = numbers[j], numbers[min_index]
            
selection_sort(numbers)

print(numbers)

[15, 25, 35, 45, 55, 65, 75, 85, 95, 105]

In [ ]:
# Чтение чисел из stdin
numbers = [45, 35, 25, 55, 15, 65, 95, 85, 105, 75]

# Допишите ваш код здесь

def insertion_sort(numbers):
    n = len(numbers)
    for i in range(1, n):
        insert_index = i
        current_value = numbers[i]
        for j in range(i - 1, -1, -1):
            if numbers[j] > current_value:
                numbers[j + 1] = numbers[j]
                insert_index = j
            else:
                break
        numbers[insert_index] = current_value
            
insertion_sort(numbers)

print(numbers)

[15, 25, 35, 45, 55, 65, 75, 85, 95, 105]
[15, 25, 35, 45, 55, 65, 75, 85, 95, 105]

# Tail

In [2]:
prices = 'яблоко 99; апельсин 99; вишня 147'

# Ожидаемый результат:
# new_prices = {'яблоко': 94.05, 'апельсин': 94.05, 'вишня': 139.65}

prices = {item.split()[0]: float(item.split()[1]) for item in prices.split('; ')}
print(prices)

new_prices = dict(map(lambda item: (item[0], item[1] * 0.95), prices.items()))
new_prices

{'яблоко': 99.0, 'апельсин': 99.0, 'вишня': 147.0}

{'яблоко': 94.05, 'апельсин': 94.05, 'вишня': 139.65}

In [3]:
code = 'abcba'

n = len(code) // 2

code[:n], code[-n:]

('ab', 'ba')

In [4]:
# Дана строка code, содержащая символьный код. Необходимо написать функцию almost_symmetric(), 
# которая принимает строку и возвращает True, если строка является почти палиндромом, False в противном случае.
# Строка называется почти палиндромом, если в ней можно изменить ровно один символ так, 
# чтобы она стала палиндромом (читалась одинаково слева направо и справа налево):
# almost_symmetric(code) → True или False
                  
# где значение — это булево значение, указывающее, является ли строка почти симметричной.

code = 'abbс'
n = len(code) // 2
print(sum([code[i] != code[-i-1] for i in range(len(code) // 2)]) == 1)

code = 'abcba'
n = len(code) // 2
print(sum([code[i] != code[-i-1] for i in range(len(code) // 2)]) == 1)

True
False

In [5]:
# Загрузка данных по ссылке
df = pd.read_csv('https://raw.githubusercontent.com/esabunor/MLWorkspace/master/melb_data.csv').drop(columns='Unnamed: 0')
df.head()  # выводим первые строки для проверки

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [6]:
df.query("Price < 3_000_000 and (Type == 'h' or YearBuilt > 2015)")

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18390,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
18392,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
18393,Yallambie,17 Amaroo Wy,4,h,1100000.0,S,Buckingham,26/08/2017,12.7,3085.0,...,3.0,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
18394,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
18395,Yarraville,33 Freeman St,4,h,1050000.0,VB,Village,26/08/2017,6.3,3013.0,...,2.0,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

In [7]:
round(df['Distance'].std())

6

In [8]:
df['Propertycount'].max()

21650.0

In [9]:
value = 'Melbourne'

column_names = df.columns[df.isin([value]).any()].tolist()
print(column_names)  # ['B']

['Suburb', 'SellerG', 'CouncilArea']

In [10]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [11]:
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'area': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]
})

countries_df

     country  population      area
0     Англия       56.29    133396
1     Канада       38.05   9984670
2        США      322.28   9826630
3     Россия      146.24  17125191
4    Украина       45.50    603628
5   Беларусь        9.50    207600
6  Казахстан       17.04   2724902

In [12]:
countries_df['density'] = countries_df['population'] / countries_df['area'] * 1_000_000
round(countries_df['density'].mean(), 2)

84.93

In [13]:
countries_df['density']

0    421.976671
1      3.810842
2     32.796595
3      8.539467
4     75.377550
5     45.761079
6      6.253436
Name: density, dtype: float64

In [14]:
s = 'abcde'
print(f'{s:2}')

abcde

In [15]:
melb_df = pd.read_csv('data/melb_data_fe.csv')
melb_df.head()

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend
0,Abbotsford,2,house,1480000.0,S,Biggin,2016-03-12,2.5,3067,2,...,144.9984,Northern Metropolitan,4019,25.20,-0.231707,3,46,5,St,1
1,Abbotsford,2,house,1035000.0,S,Biggin,2016-04-02,2.5,3067,2,...,144.9934,Northern Metropolitan,4019,15.80,-0.327660,4,116,5,St,1
2,Abbotsford,3,house,1465000.0,SP,Biggin,2017-04-03,2.5,3067,3,...,144.9944,Northern Metropolitan,4019,18.75,0.056338,4,117,0,St,0
3,Abbotsford,3,house,850000.0,PI,Biggin,2017-04-03,2.5,3067,3,...,144.9969,Northern Metropolitan,4019,15.75,0.145455,4,47,0,other,0
4,Abbotsford,4,house,1600000.0,VB,Nelson,2016-04-06,2.5,3067,3,...,144.9941,Northern Metropolitan,4019,17.75,0.083969,4,2,2,St,0

In [16]:
mask1 = melb_df['AreaRatio'] <= -0.5

mask2 = melb_df['Type'] == 'townhouse'

mask3 = melb_df['SellerG'] == 'Nelson'

melb_df[mask1 & mask2 & mask3].sort_values(by=['Date', 'AreaRatio'],

ascending=[True, False],

ignore_index=True).loc[:, ['Date', 'AreaRatio']]

          Date  AreaRatio
0   2016-03-09  -0.773810
1   2016-03-12  -0.509485
2   2016-06-27  -0.950168
3   2016-07-16  -0.630027
4   2016-07-26  -0.783037
5   2016-08-10  -0.657609
6   2016-08-10  -0.724289
7   2016-08-10  -0.782195
8   2016-08-22  -0.539192
9   2016-08-28  -0.701068
10  2017-05-13  -0.614679
11  2017-06-17  -0.901370
12  2017-08-04  -0.963311
13  2017-08-19  -0.842167

In [17]:
melb_df.head()

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend
0,Abbotsford,2,house,1480000.0,S,Biggin,2016-03-12,2.5,3067,2,...,144.9984,Northern Metropolitan,4019,25.20,-0.231707,3,46,5,St,1
1,Abbotsford,2,house,1035000.0,S,Biggin,2016-04-02,2.5,3067,2,...,144.9934,Northern Metropolitan,4019,15.80,-0.327660,4,116,5,St,1
2,Abbotsford,3,house,1465000.0,SP,Biggin,2017-04-03,2.5,3067,3,...,144.9944,Northern Metropolitan,4019,18.75,0.056338,4,117,0,St,0
3,Abbotsford,3,house,850000.0,PI,Biggin,2017-04-03,2.5,3067,3,...,144.9969,Northern Metropolitan,4019,15.75,0.145455,4,47,0,other,0
4,Abbotsford,4,house,1600000.0,VB,Nelson,2016-04-06,2.5,3067,3,...,144.9941,Northern Metropolitan,4019,17.75,0.083969,4,2,2,St,0

In [18]:
# Найдите дома (Type) с количеством жилых комнат (Rooms) больше 3. 
# Отсортируйте полученную таблицу сначала по возрастанию числа комнат, 
# а затем по убыванию средней площади комнат (MeanRoomsSquare). 
# Индексы таблицы замените на новые. Какая цена будет у объекта в строке 7? 
# Ответ запишите в виде целого числа.

mask1 = melb_df['Type'] == 'house'
mask2 = melb_df['Rooms'] > 3

melb_df[mask1 & mask2].sort_values(by=['Rooms', 'MeanRoomsSquare'], ascending=[True, False], ignore_index=True).loc[7, 'Price']

2600000.0

In [19]:
melb_df.groupby('Regionname')['SellerG'].agg('count')

Regionname
Eastern Metropolitan          1471
Eastern Victoria                53
Northern Metropolitan         3890
Northern Victoria               41
South-Eastern Metropolitan     450
Southern Metropolitan         4695
Western Metropolitan          2948
Western Victoria                32
Name: SellerG, dtype: int64

In [20]:
# Какой регион имеет наименьшее стандартное отклонение по стоимости недвижимости (Price)?

melb_df.groupby('Regionname', as_index=False).aggregate({'Price': 'std'}).sort_values('Price').style.format({'Price': '{:,.2f}'})

In [35]:
# Сгруппируйте данные по признаку количества комнат и 
# найдите среднюю цену объектов недвижимости в каждой группе. 
# В качестве ответа запишите количество комнат, для которых средняя цена наибольшая.

melb_df.groupby('Rooms', as_index=False).aggregate({'Price': 'mean'}).sort_values('Price', ascending=False).style.format({'Price': '{:,.2f}'})